### ISSUE TITLE
Steam streaming client blackscreens and hangs or crashes

### ISSUE THREAD

**Issue by timbarrass** [ecalder6/azure-gaming#28] opened 2019-04-26 21:37 UTC
First of all - thanks for all the efforts in getting this automated!

I can deploy and connect to an NV VM fine. I can download and install Steam, and the Battle.Net client and can start World of Warcraft, and even interact with it a bit over RDP.

However, when I try to stream the screen just goes black, and the streaming client either returns after a few seconds or hangs. I can hear game music playing in the first instance. Steam mention this specifically: https://support.steampowered.com/kb_article.php?ref=3629-RIAV-1617#blackscreen.

~~I've updated the latest NVidia drivers but: the download page warns that a restart would be required. I assume if I want to do that then I'll need a managed disk? Attempting it anyway (without restarting the VM) doesn't improve things.~~

~~The same Steam resource suggests a couple of other options, including testing and adjusting MTU settings. I'll be attempting those soon but~~ thought I'd raise this as an issue here in case it'd been seen and there was an obvious solution.

EDIT: I misunderstood the managed OS disk point. MTU settings are at what Steam recommend.

**Comment by timbarrass** [comment] 2019-04-27 07:16
I installed Parsec instead, following: https://support.parsecgaming.com/hc/en-us/articles/115002702331-Setting-Up-Hosting-On-Windows and it (probably*) works out of the box. I'll not pursue the Steam route any further for now, thought I'd recap here.

* I *did* enable remote COM activation and launch in my server settings on spotting some (possibly spurious) server event log errors.

**Comment by ecalder6** [comment] 2019-05-07 18:35
Hmm I'll see if I can repro this problem. In the future I may add steaming software like Parsec as an alternative to steam in-home streaming in the script.

**Comment by AmineI** [comment] 2020-07-03 13:42
Looks like a dupe of #37 , with the difference that steam now shows a splashscreen instead of a blackscreen.

If it is, it could be fixed the same way : Use C:/disconnect.lnk before attempting to stream. Steam streaming may conflict with RDP.

**Closed** 2020-07-04 20:17 UTC
